# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3edae433290ff66aa6b991d51e842eeb"
application_url = "https://serve-bangkok-drops-mazda.trycloudflare.com"
embedded = true
name = "jean-mvp-2"
handle = "jean-mvp-2"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jean-personalization.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://serve-bangkok-drops-mazda.trycloudflare.com/auth/callback",
  "https://serve-bangkok-drops-mazda.trycloudflare.com/auth/shopify/callback",
  "https://serve-bangkok-drops-mazda.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://serve-bangkok-drops-mazda.trycloudflare.com"
subpath = "twitter-recommendations"
prefix = "proxy"
